# Flock warning: LOCK_EX serializes only flock holders. mint_invite_token and
# create_user use load->save without flock (D-01). The single-use consume
# guarantee remains intact because two concurrent consumes BOTH attempt LOCK_EX
# on auth.json; the second waits, then re-reads the new inode and finds
# consumed=True.
'''auth_store._users — user registry CRUD and invite token helpers.'''
import fcntl
import hashlib
import hmac
import json
import logging
import os
import secrets
import uuid
from datetime import datetime, timedelta, timezone
from pathlib import Path

import bcrypt as _bcrypt

from auth_store._io import (
  _atomic_write_unlocked,
  _default_auth_data,
  _resolve_path,
  load_auth,
  save_auth,
)
from auth_store._schema import (
  _ensure_aware,
  _normalize_v2,
)
from system_params import INVITE_TOKEN_TTL_DAYS

logger = logging.getLogger(__name__)

_VALID_ROLES = {'admin', 'ff'}


# ---------------------------------------------------------------------------
# Typed exception classes (D-11, SC-4)
# ---------------------------------------------------------------------------

class InviteAlreadyConsumed(ValueError):
  pass


class InviteExpired(ValueError):
  pass


# ---------------------------------------------------------------------------
# Password hashing helpers (Phase 37 D-06)
# ---------------------------------------------------------------------------

def hash_password(plaintext: str) -> str:
  '''Phase 37 D-06: bcrypt hash with OWASP minimum rounds=12.

  ENFORCES 72-byte cap (review consensus #9) — bcrypt silently truncates beyond
  72 bytes which is a footgun for security-sensitive passwords. We raise
  ValueError at the boundary instead of accepting an effectively-truncated
  password.

  Raises:
    TypeError: if plaintext is not a str.
    ValueError: if len(plaintext.encode('utf-8')) > 72.
  '''
  if not isinstance(plaintext, str):
    raise TypeError('plaintext must be str')
  encoded = plaintext.encode('utf-8')
  if len(encoded) > 72:
    raise ValueError(
      f'password byte length {len(encoded)} exceeds 72 (bcrypt limit); shorten the password'
    )
  return _bcrypt.hashpw(encoded, _bcrypt.gensalt(rounds=12)).decode('utf-8')


def verify_password(plaintext: str, stored_hash: str | None) -> bool:
  '''Timing-safe bcrypt verification. Fail-closed on any exception.

  bcrypt.checkpw uses constant-time comparison internally. Returns False for
  None hash, malformed hash, or any encoding/validation error — never raises.
  '''
  try:
    return _bcrypt.checkpw(
      plaintext.encode('utf-8'),
      stored_hash.encode('utf-8'),  # type: ignore[union-attr]
    )
  except Exception:  # noqa: BLE001
    return False


# ---------------------------------------------------------------------------
# Module-private helpers
# ---------------------------------------------------------------------------

def _read_auth_unlocked(resolved: Path) -> dict:
  '''Caller MUST hold LOCK_EX on the file before calling this — returns
  potentially-unmigrated data. Always run _normalize_v2 on the result
  before using users/pending_invites fields. Returns _default_auth_data()
  if the file does not exist or is empty/whitespace-only.
  '''
  try:
    text = resolved.read_text(encoding='utf-8')
  except FileNotFoundError:
    return _default_auth_data()
  if not text.strip():
    return _default_auth_data()
  try:
    return json.loads(text)
  except (json.JSONDecodeError, UnicodeDecodeError):
    logger.warning('[Auth] corrupt auth.json at %s; using defaults inside lock', resolved)
    return _default_auth_data()


def _verify_token(unhashed_token: str, stored_hash: str) -> bool:
  '''Timing-safe comparison. Fail-closed on malformed stored_hash. Never raises.'''
  if not isinstance(stored_hash, str):
    return False
  if not stored_hash.startswith('sha256:'):
    return False
  expected = 'sha256:' + hashlib.sha256(
    unhashed_token.encode('utf-8')
  ).hexdigest()
  try:
    return hmac.compare_digest(stored_hash, expected)
  except Exception:
    return False


def _validate_user_fields(fields: dict) -> tuple[str, str]:
  '''Validate caller-supplied fields. Returns (email, role).

  Raises ValueError if 'uid' is present, email is missing/empty/non-str,
  or role is not in {'admin','ff'}.
  '''
  if 'uid' in fields:
    raise ValueError("caller-supplied 'uid' is forbidden; uid is generated by storage")
  email = fields.get('email')
  if not isinstance(email, str) or not email:
    raise ValueError("'email' is required and must be a non-empty string")
  role = fields.get('role', 'ff')
  if role not in _VALID_ROLES:
    raise ValueError(f"'role' must be one of {_VALID_ROLES!r}; got {role!r}")
  return email, role


# ---------------------------------------------------------------------------
# User registry CRUD
# ---------------------------------------------------------------------------

def create_user(fields: dict, path: Path | None = None) -> dict:
  '''Append a new User row to auth.json. No flock (D-03).
  uid is generated server-side as uuid4().hex; caller-supplied uid rejected.
  '''
  email, role = _validate_user_fields(fields)
  data = load_auth(path=path)
  user = {
    'uid': uuid.uuid4().hex,
    'email': email,
    'role': role,
    'created_at': datetime.now(timezone.utc).isoformat(),
    'disabled': False,
    'password_hash': fields.get('password_hash'),  # None for admin-only rows (CR-03)
  }
  data['users'].append(user)
  save_auth(data, path=path)
  return user


def get_user(uid: str, path: Path | None = None) -> dict | None:
  '''Return the User dict for uid, or None if not found.'''
  data = load_auth(path=path)
  for row in data.get('users', []):
    if row.get('uid') == uid:
      return row
  return None


def get_user_by_email(email: str, path: Path | None = None) -> dict | None:
  '''Return the User dict matching email (case-insensitive), or None if not found.

  Case-insensitive equality: both the argument and the stored email are lowercased
  before comparison. Returns the first match when duplicates exist (Phase 34 does
  not enforce email uniqueness — see 35-REVIEWS.md OpenCode/Codex consensus).
  '''
  needle = email.lower() if isinstance(email, str) else ''
  data = load_auth(path=path)
  for row in data.get('users', []):
    stored = row.get('email', '')
    if isinstance(stored, str) and stored.lower() == needle:
      return row
  return None


def list_users(path: Path | None = None) -> list:
  '''Return all User rows.'''
  return load_auth(path=path).get('users', [])


def set_user_disabled(
  uid: str, disabled: bool, path: Path | None = None,
) -> bool:
  '''Flip disabled flag. Row RETAINED (RBAC-04). Returns False without
  writing if uid is unknown. Reversible.
  '''
  data = load_auth(path=path)
  for row in data.get('users', []):
    if row.get('uid') == uid:
      row['disabled'] = disabled
      save_auth(data, path=path)
      return True
  return False


# ---------------------------------------------------------------------------
# Invite token helpers
# ---------------------------------------------------------------------------

def mint_invite_token(
  invited_by_uid: str,
  email: str,
  path: Path | None = None,
) -> tuple[str, str]:
  '''Create and store a pending invite token. No flock (D-01).
  Returns (raw_token, expires_at_iso). Only sha256 hash is persisted.
  '''
  raw = secrets.token_urlsafe(32)
  token_hash = 'sha256:' + hashlib.sha256(raw.encode('utf-8')).hexdigest()
  now = datetime.now(timezone.utc)
  expires = now + timedelta(days=INVITE_TOKEN_TTL_DAYS)
  data = load_auth(path=path)
  invite = {
    'token_hash': token_hash,
    'email': email,
    'invited_by': invited_by_uid,
    'created_at': now.isoformat(),
    'expires_at': expires.isoformat(),
    'consumed': False,
    'consumed_at': None,
  }
  data['pending_invites'].append(invite)
  save_auth(data, path=path)
  return (raw, expires.isoformat())


def consume_and_create_user(
  unhashed_token: str,
  new_user_fields: dict,
  password_hash: str | None = None,
  path: Path | None = None,
) -> dict:
  '''Atomically validate an invite token and create a User row.

  Single-use guarantee: the full validate→mark-consumed→append-user→write
  sequence runs inside a single LOCK_EX window, preventing two concurrent
  callers from both succeeding on the same token.

  NOTE — flock-on-inode vs os.replace semantics:
    LOCK_EX serializes other flock holders against this critical section.
    After _atomic_write_unlocked swaps in a new inode via os.replace, the
    lock fd refers to the old inode; this is intentional. Subsequent flock
    holders re-open the new inode and wait. Non-flock writers (mint_invite_token,
    create_user) can race per D-01 — accepted for F&F scale.

  Raises:
    ValueError: if new_user_fields fails _validate_user_fields (before lock).
    InviteAlreadyConsumed: if token not found OR already consumed.
    InviteExpired: if matching unconsumed invite has expired.
  '''
  # Validate fields BEFORE taking the lock — fail fast.
  email, role = _validate_user_fields(new_user_fields)

  resolved = _resolve_path(path)
  lock_fd = os.open(str(resolved), os.O_RDWR | os.O_CREAT, 0o600)
  try:
    fcntl.flock(lock_fd, fcntl.LOCK_EX)
    try:
      raw_data = _read_auth_unlocked(resolved)
      data = _normalize_v2(raw_data)  # HIGH-fix: backfill v2 keys inside lock
      if data.get('schema_version', 0) < 2:
        raise RuntimeError(
          f'[Auth] expected schema_version>=2 before invite flow; got {data.get("schema_version")!r}'
        )

      # Scan pending_invites for a matching hash.
      matched_row = None
      for row in data['pending_invites']:
        if _verify_token(unhashed_token, row.get('token_hash', '')):
          matched_row = row
          break

      if matched_row is None or matched_row.get('consumed') is True:
        raise InviteAlreadyConsumed('invalid or already consumed invite token')

      try:
        expires_dt = _ensure_aware(datetime.fromisoformat(matched_row['expires_at']))
      except (TypeError, ValueError):
        raise InviteExpired('invite token has unparseable expiry')
      if datetime.now(timezone.utc) > expires_dt:
        raise InviteExpired('invite token expired')

      invite_email = matched_row.get('email', '')
      if invite_email.lower() != email.lower():
        raise ValueError(
          f'email mismatch: invite issued for {invite_email!r}, '
          f'got {email!r}'
        )

      matched_row['consumed'] = True
      matched_row['consumed_at'] = datetime.now(timezone.utc).isoformat()

      new_user = {
        'uid': uuid.uuid4().hex,
        'email': email,
        'role': role,
        'created_at': datetime.now(timezone.utc).isoformat(),
        'disabled': False,
        'password_hash': password_hash,  # None for legacy callers; str for invite wizard (D-06)
      }
      data['users'].append(new_user)

      payload = json.dumps(data, indent=2, ensure_ascii=False) + '\n'
      _atomic_write_unlocked(payload, resolved)
      return new_user
    finally:
      fcntl.flock(lock_fd, fcntl.LOCK_UN)
  finally:
    os.close(lock_fd)


# ---------------------------------------------------------------------------
# Invite query helpers (Phase 37)
# ---------------------------------------------------------------------------

def _peek_invite_token(unhashed_token: str, path: Path | None = None) -> str:
  '''Validate invite token and return email WITHOUT consuming.

  WR-05: timing note — the loop breaks on the FIRST matching row (happy path),
  so it does NOT walk the full list before returning. Full-list traversal only
  occurs when NO row matches (not-found path). The minor timing oracle (list
  length enumerable via response time on hit vs. miss) is an accepted tradeoff
  at this scale.
  Raises InviteAlreadyConsumed if token is consumed, not found, or invalid.
  Raises InviteExpired if the matching invite has passed expires_at.
  '''
  data = _normalize_v2(load_auth(path=path))
  for row in data.get('pending_invites', []):
    if _verify_token(unhashed_token, row.get('token_hash', '')):
      if row.get('consumed'):
        raise InviteAlreadyConsumed('already consumed')
      try:
        expires_dt = _ensure_aware(datetime.fromisoformat(row['expires_at']))
      except (TypeError, ValueError):
        raise InviteExpired('unparseable expiry')
      if datetime.now(timezone.utc) > expires_dt:
        raise InviteExpired('expired')
      return row.get('email', '')
  raise InviteAlreadyConsumed('not found or invalid token')


def list_pending_invites(path: Path | None = None) -> list:
  '''Return all PendingInvite rows (consumed + active).'''
  return load_auth(path=path).get('pending_invites', [])


def revoke_invite(token_hash: str, path: Path | None = None) -> bool:
  '''Mark a pending invite row consumed by token_hash. Returns True if a matching
  unconsumed row was found and updated; False otherwise.

  FLOCK RATIONALE (review consensus #12): This helper deliberately does NOT acquire flock,
  while consume_and_create_user does. The asymmetry is safe because:

  1. Idempotent: revoking an already-consumed row is a no-op (we return False).
  2. Single-field overwrite: we set consumed=True and consumed_at=<iso> — both
     fields converge under any interleaving of concurrent revoke calls.
  3. Atomic at OS level: save_auth uses os.replace which is atomic at the inode
     level for typical auth.json sizes (single-digit KB). A concurrent unflocked
     write may overwrite another unflocked write's inode (lost-update race) — but
     for revoke the lost write is also a revoke, producing the same final state.
  4. Security boundary preserved: consume_and_create_user uses flock to atomically
     (a) verify token existence, (b) mark consumed, (c) append User. revoke_invite
     only does (b); the security-critical token->user transition is still flock-protected.

  DO NOT call this helper concurrently with consume_and_create_user on the same
  token — the consume path holds flock and may overwrite the revoke. If admin
  revokes while invitee accepts, the consume wins (user is created); admin can
  still see the new user in /admin/users. Phase 34 D-01 explicitly accepts this
  tradeoff to keep revoke simple.
  '''
  data = load_auth(path=path)
  for row in data.get('pending_invites', []):
    if row.get('token_hash') == token_hash and not row.get('consumed'):
      row['consumed'] = True
      row['consumed_at'] = datetime.now(timezone.utc).isoformat()
      save_auth(data, path=path)
      return True
  return False
